ARRAY CREATION 

In [16]:
#QUESTION 1:Create a numpy array of size 10, filled with zeros.

a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
#QUESTION 2:Create a numpy array with values ranging from 10 to 49

b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [73]:
#QUESTION 3:Create a numpy matrix of 2*2 integers, filled with ones.

c = np.ones((2,2)  , dtype = np.int8)
c

array([[1, 1],
       [1, 1]], dtype=int8)

In [74]:
#QUESTION 4:Create a numpy matrix of 3*2 float numbers, filled with ones.

d = np.ones((3,2)  , dtype = float)
d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [163]:
#QUESTION 5:Given the X numpy array, create a new numpy array with the same shape and type as X,filled with ones.

x = np.array([1,2,3,4])
print(x.dtype)

e = np.ones(x.shape , dtype = x.dtype)
print(e)
print(e.dtype)

int32
[1 1 1 1]
int32


In [164]:
#QUESTION 6:Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

x = np.array([[5,10,15],[20,25,30],[35,40,45]]) 
print(x.dtype)

f = np.zeros(x.shape , dtype = x.dtype)
print(f)
print(f.dtype)

int32
[[0 0 0]
 [0 0 0]
 [0 0 0]]
int32


In [52]:
#QUESTION 7:Create a numpy matrix of 4*4 integers, filled with fives.

g = np.full((4,4) , 5 , dtype = np.int8)
g

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int8)

In [166]:
#QUESTION 8:Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

p = np.array([[5,10,15],[20,25,30],[35,40,45]]) 
print(p.dtype)

h = np.full(p.shape , 7 ,dtype = p.dtype)
print(h)
print(h.dtype)

int32
[[7 7 7]
 [7 7 7]
 [7 7 7]]
int32


In [59]:
#QUESTION 9:Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
#QUESTION 10:Create a numpy array, filled with 3 random integer values between 1 and 10.

j = np.random.randint(1 , 10 , size = 3)
j

array([9, 8, 3])

In [72]:
#QUESTION 11:Create a 3*3*3 numpy matrix, filled with random float values.

k = np.random.random((3,3,3))
k

array([[[0.55256189, 0.8459472 , 0.39133596],
        [0.02513178, 0.85306667, 0.28517072],
        [0.99555598, 0.7987358 , 0.62176643]],

       [[0.63208802, 0.41332566, 0.00545633],
        [0.62651441, 0.02160463, 0.79773301],
        [0.38425678, 0.78005745, 0.17074886]],

       [[0.27979583, 0.30559823, 0.88397202],
        [0.64631079, 0.76297948, 0.4168909 ],
        [0.28616541, 0.5496666 , 0.28478334]]])

In [45]:
#QUESTION 12:Create a numpy array with numbers from 1 to 10

l = np.arange(1,11)
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [146]:
#QUESTION 13:Create a numpy array with the odd numbers between 1 to 10

m = np.arange(1,10,2)
m

array([1, 3, 5, 7, 9])

In [139]:
#QUESTION 14:Create a numpy array with numbers from 1 to 10, in descending order.

n = np.arange(10,0,-1)
n

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [41]:
#QUESTION 15:Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

o = np.arange(9).reshape(3,3)
o

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

ARRAY INDEXATION

In [121]:
#QUESTION 1:Given the X numpy array, show it's first element

import numpy as np

X = np.array(["a","b","c","d","e"])

first = X[0]  
print(first)

a


In [122]:
#QUESTION 2:Given the X numpy array, show it's last element

X = np.array(["a","b","c","d","e"])

last = X[-1]
print(last)

e


In [123]:
#QUESTION 3:Given the X numpy array, show it's first three elements

X = np.array(["a","b","c","d","e"])

first_three = X[:3]
print(first_three)

['a' 'b' 'c']


In [124]:
#QUESTION 4:Given the X numpy array, show all middle elements

X = np.array(["a","b","c","d","e"])

middle = X[1:-1]
print(middle)

['b' 'c' 'd']


In [125]:
#QUESTION 5:Given the X numpy array, show the elements in reverse position.

X = np.array(["a","b","c","d","e"])

reverse_post = X[::-1]
print(reverse_post)

['e' 'd' 'c' 'b' 'a']


In [126]:
#QUESTION 6:Given the X numpy array, show the elements in an odd position.

X = np.array(["a","b","c","d","e"])

odd_position = X[::2]
print(odd_position)

['a' 'c' 'e']


In [127]:
#QUESTION 7:Given the X numpy matrix, show the first row elements.

x = np.array([[5,10,15],[20,25,30],[35,40,45]])

firstrow = x[0]
print(firstrow)

[ 5 10 15]


In [128]:
#QUESTION 8:Given the X numpy matrix, show the last row elements.

x = np.array([[5,10,15],[20,25,30],[35,40,45]])

lastrow = x[-1]
print(lastrow)

[35 40 45]


In [129]:
#QUESTION 9:Given the X numpy matrix, show the first element on first row

x = np.array([[5,10,15],[20,25,30],[35,40,45]])

firstE_firstR = x[0][0]
print(firstE_firstR)

5


In [130]:
#QUESTION 10:Given the X numpy matrix, show the last element on last row.

x = np.array([[5,10,15],[20,25,30],[35,40,45]])

lastE_lastR = x[-1][-1]
print(lastE_lastR)

45


In [131]:
#QUESTION 11:Given the X numpy matrix, show the first two elements on the first two rows.

x = np.array([[5,10,15],[20,25,30],[35,40,45]])

start = x[:2,:2]
print(start)

[[ 5 10]
 [20 25]]


In [132]:
#QUESTION 12:Given the X numpy matrix, show the last two elements on the last two rows

x = np.array([[5,10,15],[20,25,30],[35,40,45]])

end = x[-2:,-2:]
print(end)

[[25 30]
 [40 45]]


ARRAY MANIPULATION

In [112]:
#QUESTION 1:Convert the given integer numpy array to float

z = np.array([1,2,3,4] , dtype = float)
print(z.dtype)
print(z)

float64
[1. 2. 3. 4.]


In [117]:
#QUESTION 2:Reverse the given numpy array (first element becomes last)

z = np.array([1,2,3,4])

y = z[::-1]
y

array([4, 3, 2, 1])

In [106]:
#QUESTION 3:Given the X numpy array, set the fifth element equal to 1

X = np.array(["a","b","c","d","e","f"])

X[5] = 1
X

array(['a', 'b', 'c', 'd', 'e', '1'], dtype='<U1')

In [118]:
#QUESTION 4:Given the X numpy matrix, change the last row with all 1

x = np.array([[5,10,15],[20,25,30],[35,40,45]])

x[-1] = 1
x

array([[ 5, 10, 15],
       [20, 25, 30],
       [ 1,  1,  1]])

In [119]:
#QUESTION 5:Given the X numpy matrix, add 5 to every element

x = np.array([[5,10,15],[20,25,30],[35,40,45]])

x +=5
x

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])